# Generated by Django 3.2 on 2023-02-28 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evgeny', '0002_alter_title_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre_Title',
        ),
    ]
