# Generated by Django 3.2 on 2023-03-01 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evgeny', '0004_alter_title_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre_Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evgeny.genre')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evgeny.title')),
            ],
        ),
    ]
