# Generated by Django 3.2 on 2023-03-01 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evgeny', '0005_genre_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre_Title',
        ),
    ]
