# Generated by Django 3.2 on 2023-03-01 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evgeny', '0007_auto_20230301_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['-year']},
        ),
    ]
