# Generated by Django 3.2 on 2023-03-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0005_auto_20230303_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
