# Generated by Django 3.2 on 2023-03-07 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0006_alter_genre_slug'),
        ('titles', '0008_alter_title_name'),
    ]

    operations = [
    ]
